<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%user_address}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property integer $country_id
 * @property integer $state_id
 * @property integer $city_id
 * @property string $csc_name
 * @property string $csc_name_en
 * @property string $street
 * @property string $phone
 * @property integer $status
 */
class UserAddress extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_address}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'street', 'phone'], 'required'],
            [['user_id', 'country_id', 'state_id', 'city_id', 'status'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['csc_name', 'csc_name_en', 'street'], 'string', 'max' => 500],
            [['phone'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'name' => '仓库名称',
            'country_id' => 'Country ID',
            'state_id' => 'State ID',
            'city_id' => 'City ID',
            'csc_name' => '地区（中文）',
            'csc_name_en' => '地区（英文）',
            'street' => '详细地址',
            'phone' => '电话',
            'status' => '状态',
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
//     public function getPlace()
//     {
//         return $this->hasOne(Place::className(), ['id' => 'city_id']);
//     }
//     //获得地区联动
//     public $place_id_1  = 0;
    
//     public function afterFind()
//     {
//         parent::afterFind(); // TODO: Change the autogenerated stub
//         $this->setPlaces($this->place_id);
//     }
    
//     private function setPlaces($place_id)
//     {
//         $place = new Place();
//         //市级信息
//         $place_info = $place::findOne($place_id);
//         //print_r($place_info);exit();
//         if($place_info){
//             //获得省级id
//             $this->place_id_1 = $place_info->pid;
//         }
//     }
}
