<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%user_address}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property integer $country_id
 * @property integer $state_id
 * @property integer $city_id
 * @property string $csc_name
 * @property string $csc_name_en
 * @property string $street
 * @property string $phone
 * @property integer $status
 */
class UserAddress extends \yii\db\ActiveRecord
{
    public $city_id_1  = 0;
    const STATUS_ACTIVE = 0;
    const STATUS_DEFAULT = 1;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_address}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'street', 'phone', 'city_id'], 'required'],
            [['country_id', 'state_id', 'city_id', 'status'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['csc_name', 'csc_name_en', 'street'], 'string', 'max' => 500],
            [['phone'], 'string', 'max' => 50],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => Place::className(), 'targetAttribute' => ['city_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '仓库名称',
            'city_id' => '城市',
            'csc_name' => '地区（中文）',
            'csc_name_en' => '地区（英文）',
            'street' => '详细地址',
            'phone' => '电话',
            'status' => '状态',
        ];
    }
    
    public static function allStatus()
    {
        return [self::STATUS_ACTIVE=>'正常',self::STATUS_DEFAULT=>'默认'];
    }
    
    /**
     * 获得后台商品状态并转为中文显示
     */
    public function getStatusStr()
    {
        return $this->status==self::STATUS_ACTIVE?'正常':self::STATUS_DEFAULT?'默认':'已删除';
    }
    
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->setCitys($this->city_id);
    }
    
    private function setCitys($city_id)
    {
        $category = new Category();
        $place = new Place();
        //城市信息
        $place_info = $place::findOne($city_id);
        if($place_info){
            $this->city_id_1 = $place_info->pid;
        }
    }
}
